/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.62).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package my.tests.max_finder_with_swagger.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;


@Validated
public interface FindApi {

    @Operation(summary = "Find n-th max number", description = "Multiple status values can be provided with comma separated strings", tags = {"find"})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))),

            @ApiResponse(responseCode = "400", description = "Invalid value")})
    @RequestMapping(value = "/find",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<String> getNMaxNumber(
            @NotNull @Parameter(in = ParameterIn.QUERY, description = "Max number from top", required = true, schema = @Schema(defaultValue = "1", minimum = "1"))
            @Valid @RequestParam(value = "n", required = true, defaultValue = "1") Integer n,
            @NotNull @Parameter(in = ParameterIn.QUERY, description = "Path to local file", required = true, schema = @Schema())
            @Valid @RequestParam(value = "p", required = true) String p
    );

}

